services:
  app:
    container_name: home-site
    image: home:latest
    ports:
      - "12445:12445"
    networks:
      - web-network
    restart: unless-stopped

networks:
  web-network:
    external: true
